flowchart TB

    A("Intrinsic Properties")
    V("Validity Check")
    B("Valid Samples")
    X("Rejected Samples")
    C("Magnet Type Classifier")

    A --> V
    V -->|Invalid| X
    V -->|Valid| B
    B --> C

    subgraph HM["Hard Model"]
        R1("Hard Surrogate Model")
        R1 --> P1("Hard Properties")
    end

    subgraph SM["Soft Model"]
        R2("Soft Surrogate Model")
        R2 --> P2("Soft Properties")
    end

    C -->|Hard| R1
    C -->|Soft| R2